name: Deploy Kraken to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    env: 
      GITHUB_WORSPACE: /home/ec2-user/
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env file
      - run: |
          sudo newgrp docker
          echo "TOKEN=${{ secrets.TOKEN }}" >> .env
          echo "GOD_ID=${{ secrets.GOD_ID }}" >> .env
        working_directory: $GITHUB_WORSPACE



