name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get -y install docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Create .env File
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

    - name: Build Docker Image
      run: |
        docker build -t my-docker-image -f path/to/Dockerfile .
    
    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          docker stop my-container || true
          docker rm my-container || true
          docker run -d --name my-container -p 80:80 --env-file .env my-docker-image


            

            
 